repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/myint/autoflake
    rev: ''
    hooks:
    -   id: autoflake
        args: ["-i","--remove-all-unused-imports"]
-   repo: https://github.com/PyCQA/isort
    rev: ''
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: pylint
        args: ["--disable=W0142,W0403,W0613,W0232,R0903,R0913,C0103,R0914,C0304,F0401,W0402,E1101,W0614,C0111,C0301"]
